[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CATPlots = "d194c7c1-4081-4169-ba52-101f65b44e42"
ComputerAdaptiveTesting = "5a0d4f34-1f62-4a66-80fe-87aba0485488"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FittedItemBanks = "3f797b09-34e4-41d7-acf6-3302ae3248a5"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
ItemResponseDatasets = "e47bb625-2913-44fb-8b24-b88572ac4ea9"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
PsychometricsBazaarBase = "b0d9cada-d963-45e9-a4c6-4746243987f1"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
RDataGet = "a115732e-4334-4ecb-8ea3-f683e7f66d4d"
RIrtWrappers = "3c499bf4-8795-40ff-83c0-5639be88f347"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SuperFastCat = "db00f2e6-4305-4326-a702-91362453c7b4"
